/*
    In this example, we will learn how to delete a record from mongoDB collection using the id


* */

// as always we start with some database settings

const {MongoClient, ObjectId} = require('mongodb');
// ObjectId is a built-in class for having access to the primary key of the records inside of the collection
// please note that this ID os automatically generated byMongoDB and you do not need to define it manually
const url = 'mongodb://localhost:27017';
const dbName = 'db_TrendInTechClass';
const collectionName = 'Users';
const client = new MongoClient(url);
// Here we enter the ID of the record which we want to delete
const recordID_toDelete = '65fc48af59fc85022fb38258'; // this ID is found in MongoDB (_id)

// here we define a delete function

async  function deleteRecord() {

    // First way
   /* try {
        await client.connect(); // connect to the MongoDB Server
        const db = client.db(dbName); // get the object of the database
        const collection = db.collection(collectionName); // get the object of the collection
        const objectIdToDelete = new ObjectId(recordID_toDelete);
        const result = await collection.deleteOne({_id: objectIdToDelete});
        if (result.deletedCount === 1) {
            console.log(`Record with ID ${recordID_toDelete} deleted successfully`);
        }
        else {
            console.log(` No Record found with ID ${recordID_toDelete}`);
        }
    }
    catch(err) {
        console.error(`Error: `, err);
    }
    finally {
        if (client) {
            await client.close();
        }
    }*/

    // second way
    try {
        await client.connect();
        console.log('Collection established');
        const database = client.db(dbName);
        const collection = database.collection(collectionName);
        console.log(`Collection '${collectionName}' is selected!`);

        // we define a filter to delete a record
        const filter = {_id: new ObjectId("65fc4a8460a42d367e81d4e6")};
        const deleteResult = await collection.deleteOne(filter);
        console.log("Document deleted: ", deleteResult.deletedCount);
    }
    catch(err) {
        console.error(`Error: `, err);
    }
    finally {
        if (client) {
            await client.close();
            console.log('Connection closed!');
        }
    }
}
deleteRecord();














