# Generated by Django 4.1.3 on 2022-12-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.book'),
        ),
    ]
