# Generated by Django 4.1.3 on 2022-12-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('b', 'Booked'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=9),
        ),
    ]
